### PR TITLE
Latest updates to the Bulgarian translation

### PR DESCRIPTION
**Pull request by RacerBG**
Integrated the latest changes.

Regards,
Georgi

### CODE REVIEW

**Comment by levinli303** [comment]
I've fixed the format issue.  @RacerBG  Does it still look good? I guess POEdit just changes the format of some strings. (I just edited the raw files directly all the time.)

**Comment by RacerBG** [comment]
> 
> 
> I've fixed the format issue. @RacerBG Does it still look good? I guess POEdit just changes the format of some strings. (I just edited the raw files directly all the time.)

Perfect. :smiley:  Sorry about that, Poedit have some automatic formatting I guess. I'm using version 3.0.

**Comment by levinli303** [comment]
@RacerBG only one new string is needed for 1.4.4 for translation, can you help with it? It is "Speed Control"

**Comment by RacerBG** [comment]
> 
> 
> @RacerBG only one new string is needed for 1.4.4 for translation, can you help with it? It is "Speed Control"

@levinli303 "Контрол на скоростта"

**Pull request merged**
