### PR TITLE
Translated Hong Kong and Nur-Sultan in Bulgarian

### PR DESCRIPTION
**Pull request by RacerBG**
Small update.

@levinli303 keep me updated if you make further changes. :)

### CODE REVIEW

**Comment by levinli303** [comment]
thanks for the help! can you also help translate the newly added strings in https://github.com/levinli303/Celestia/blob/master/po3/bg.po .

**Comment by RacerBG** [comment]
I think they are done, I found only the "Development" string.

**Comment by levinli303** [comment]
search for `msgstr ""` there should be four untranslated strings

**Comment by RacerBG** [comment]
> 
> 
> search for `msgstr ""` there should be four untranslated strings

Thank you, I found them, both PR's are ready for merge.

**Pull request merged**
