### PR TITLE
Latest updates to bg.po

### PR DESCRIPTION
**Pull request by RacerBG**
@levinli303 I believe that line 86 should be "msgid "**Add-on directory does not _exist_.**" instead of "msgid "**Add-on directory does not _exit_.**"" I corrected that already in my bg.po file.

Your updates are quite fast I congratulate you on that!

Also, can you, please, tell me what are the system requirements of the Android version? I have a bunch of phones laying around and I'm eager to test it on them (from Android 5.1.1 up to Android 10).

EDIT: From where should I download it?

Regards,
Georgi

### CODE REVIEW

**Comment by levinli303** [comment]
Thanks for catching that, I've fixed the typo, can you maybe fix your branch?

**Comment by levinli303** [comment]
Mobile Celestia is compatible with Android 5.0 and up. Please download at https://celestia.mobi

**Comment by RacerBG** [comment]
> 
> 
> Mobile Celestia is compatible with Android 5.0 and up. Please download at https://celestia.mobi

I don't know how to do that. :(

I enabled the "**Allow edits by maintainers**" if this helps.

**Comment by levinli303** [comment]
@RacerBG  I fixed in #6

**Comment by levinli303** [comment]
@RacerBG  I forgot to add strings for connecting to new screen on iOS, see the latest commit https://github.com/levinli303/Celestia/commit/3fc80831712b61f0858bd6bd74a636254ff0470b can you add Bulgarian translation for the two? thanks.

**Comment by RacerBG** [comment]
> 
> 
> @RacerBG I forgot to add strings for connecting to new screen on iOS, see the latest commit [3fc8083](https://github.com/levinli303/Celestia/commit/3fc80831712b61f0858bd6bd74a636254ff0470b) can you add Bulgarian translation for the two? thanks.

@levinli303 

"An external screen is connected, do you want to display Celestia on the external screen?"
"Свързан е външен екран, искате ли Celestia да се покаже на външния екран?"

"Failed to connect to the external screen."
"Неуспешно свързване с външния екран."

**Pull request closed without merging**
