### PR TITLE
Subtitles on multiple rows

### PR DESCRIPTION
**Pull request by RacerBG**
This change is specific for the Mobile version of Celestia and this PR makes the subtitles (hopefully) better suited for devices with smaller screens. This PR makes the subtitles on multiple rows.

@levinli303 This changes are only for the Mobile version (iOS and Android) and they are for the Bulgarian version of the demo only. The desktop version is fine as it is. I had not tested it but I believe it should be fine now.

Regards,
Georgi

### CODE REVIEW

**Comment by levinli303** [comment]
maybe you can test by copying this file to your device and opening it? or put it in the Android/data/space.celestia.mobilecelestia/files/CelestiaResources/scripts and then run from Favorites -> Scripts

**Comment by RacerBG** [comment]
> 
> 
> maybe you can test by copying this file to your device and opening it? or put it in the Android/data/space.celestia.mobilecelestia/files/CelestiaResources/scripts and then run from Favorites -> Scripts

Sure, I will do it. :)

**Comment by RacerBG** [comment]
@levinli303 It looks better now. You can merge it.

**Comment by levinli303** [comment]
I'll leave it here for now, since Mac version use this repo as well.

**Comment by RacerBG** [comment]
> 
> 
> I'll leave it here for now, since Mac version use this repo as well.

The same thing could/should be applied to the other languages as well. And I don't know what is the smallest possible supported display - 4", 5", who knows? We can try to figure that out.

**Comment by levinli303** [comment]
closing, I think this is better taken care of by https://github.com/CelestiaProject/Celestia/pull/867 which should allow frontends to layout text, in that way we have more flexible control over linebreaks.

**Comment by RacerBG** [comment]
> 
> 
> closing, I think this is better taken care of by [CelestiaProject#867](https://github.com/CelestiaProject/Celestia/pull/867) which should allow frontends to layout text, in that way we have more flexible control over linebreaks.

That's fine and indeed it's the better option.

**Pull request closed without merging**
